services:
  acme-keycloak:
    #image: quay.io/keycloak/keycloak:$KEYCLOAK_VERSION

    build:
      context: "./keycloak"
      dockerfile: "./Dockerfile" # default mgt login jmxuser:password

    #    user: "${USER}:${GROUP}"
    env_file:
      - ./keycloak-common.env
      - ./keycloak-http.env
    environment:
#      KEYCLOAK_USER: "admin"
#      KEYCLOAK_PASSWORD: "admin"
      DB_VENDOR: "h2"
      KEYCLOAK_THEME_CACHING: "false"
      KEYCLOAK_THEME_TEMPLATE_CACHING: "false"
      PROXY_ADDRESS_FORWARDING: "true"
# force usage for standalone.xml for local dev
      KEYCLOAK_CONFIG_FILE: "standalone.xml"

# Exposes Metrics via http://localhost:9990/metrics
      KEYCLOAK_STATISTICS: all

      #JAVA_OPTS: "-XX:MaxRAMPercentage=80 -XX:+UseG1GC -XX:MaxGCPauseMillis=500 -Djava.net.preferIPv4Stack=true -XX:FlightRecorderOptions=stackdepth=256"

    mem_limit: 1024m
    mem_reservation: 1024m
    cpus: 2

#      KEYCLOAK_IMPORT: "/opt/jboss/imex/custom-realm.json"
# use `docker-compose --env-file custom-keycloak.env up` to populate the KEYCLOAK_CONFIG_FILE variable.
    command:
      - "--debug"
      - "*:8787"
      - "--server-config"
      - "$KEYCLOAK_CONFIG_FILE"
      - "-b"
      - "0.0.0.0"
      - "-bmanagement"
      - "0.0.0.0"
      - "-Dwildfly.statistics-enabled=true"
#      - "-Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.SimpleLog"
    extra_hosts:
      # ${DOCKER_HOST_IP:-172.17.0.1} is host.docker.internal
      - "id.acme.test:${DOCKER_HOST_IP:-172.17.0.1}"
      - "apps.acme.test:${DOCKER_HOST_IP:-172.17.0.1}"
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8790:8790"
      - "9990:9990"
      - "127.0.0.1:8787:8787"
    volumes:
      - ../../../keycloak/themes/apps:/opt/jboss/keycloak/themes/apps:z
      - ../../../keycloak/themes/internal:/opt/jboss/keycloak/themes/internal:z
      - ../../../keycloak/themes/internal-modern:/opt/jboss/keycloak/themes/internal-modern:z
      - ../../../keycloak/config/profile.properties:/opt/jboss/keycloak/standalone/configuration/profile.properties:z
      - ../../../keycloak/imex:/opt/jboss/imex:z
# This will exposes *.sh and *.cli startup scripts that are executed by Keycloak.
      - ../../../keycloak/cli:/opt/jboss/startup-scripts:z
      - ./run/keycloak/data:/opt/jboss/keycloak/standalone/data:z
      - ./run/keycloak/logs:/opt/jboss/keycloak/standalone/logs:z
      - ./run/keycloak/perf:/opt/jboss/keycloak/standalone/perf:z
#      - ./run/keycloak/healthCheck:/opt/jboss/keycloak/standalone/healthCheck:z
# Add third-party extensions
#      - ./keycloak-ext/keycloak-metrics-spi-2.5.3-SNAPSHOT.jar:/opt/jboss/keycloak/standalone/deployments/keycloak-metrics-spi-2.5.3-SNAPSHOT.jar:z
      - ./keycloak-ext/keycloak-home-idp-discovery-18.0.0.jar:/opt/jboss/keycloak/standalone/deployments/keycloak-home-idp-discovery.jar:z
#    healthCheck:
#      command: ["CMD-SHELL", "bash /run/health_check.sh"]
#      interval: 30s
#      timeout: 10s
#      retries: 3
#      start_period: 30s
#      start_interval: 5s